---
title: "Old Faithful Eruptions"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard
library(flexdashboard)
library(plotly)
library(covid19italy)
library(ggplot2)
library(dplyr)
 library(tidyr)
italy_province2 <- italy_province %>% 
    mutate(date=as.Date(date, format= "%y/%m/%d"))%>% 
     group_by(province_code) %>%  
     arrange(desc(date)) %>%
     slice(1)

```

Column {.sidebar}
-----------------------------------------------------------------------

Waiting time between eruptions and the duration of the eruption for the
Old Faithful geyser in Yellowstone National Park, Wyoming, USA.

```{r}
selectInput("region", label = "Region:",
            choices = c("Piemonte","Valle d'Aosta","Liguria","Lombardia","P.A. Bolzano",
                        "P.A. Trento","Veneto","Friuli Venezia 
                        Giulia","Emilia-Romagna","Marche","Toscana","Umbria","Lazio","Campania","Abruzzo","Molise",                          "Puglia","Basilicata","Calabria","Sicilia","Sardegna"  ), selected = "Piemonte")

```

Column
-----------------------------------------------------------------------

### Geyser Eruption Duration

```{r}
renderPlot({
  italy_province2 %>%
  filter(date == max(date), region_name == "Lombardia") %>%
  ggplot(labels = ~province_name, values = ~total_cases,
          textinfo="label+percent",
          type = 'pie') 
})
```






